/*
 Department form
 */
package forms;

import myCompany.Tools;
import entity.Department;
import java.awt.Color;
import java.awt.event.KeyEvent;

public class frmDepartment extends javax.swing.JFrame {
     Department d= new Department();
    /**
     * Creates new form frmDepartment
     */
    public frmDepartment() {
        initComponents();
         txtNo.setBackground(new Color(0, 0, 0,1));
          txtLocation.setBackground(new Color(0, 0, 0,1));
           txtName.setBackground(new Color(0, 0, 0,1));
            txtSearch.setBackground(new Color(0, 0, 0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGroup = new javax.swing.ButtonGroup();
        btnAdd = new controls.JMyButton();
        btnubdate = new controls.JMyButton();
        btnDelete = new controls.JMyButton();
        btnGetAllRows = new controls.JMyButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new controls.JMyTextBox(15);
        txtLocation = new controls.JMyTextBox(15);
        btnBack = new controls.JMyButton();
        jLabel5 = new javax.swing.JLabel();
        rBNo = new javax.swing.JRadioButton();
        rBName = new javax.swing.JRadioButton();
        rBLocation = new javax.swing.JRadioButton();
        txtSearch = new controls.JMyTextBox(15);
        btnSerch = new controls.JMyButton();
        btnClear = new controls.JMyButton();
        btnFind = new controls.JMyButton();
        btnPrint = new controls.JMyButton();
        txtNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 165, -1, -1));

        btnubdate.setText("ubdate");
        btnubdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnubdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 165, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 165, -1, -1));

        btnGetAllRows.setText("get all rows");
        btnGetAllRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllRowsActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetAllRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Department");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 6, -1, -1));

        tblTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "depNo", "depName", "location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblTestMouseEntered(evt);
            }
        });
        tblTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblTestKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTestKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblTest);
        tblTest.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 165, 407, 108));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 99, -1, -1));

        jLabel3.setText("No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 58, -1, -1));

        jLabel4.setText("Location");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 140, -1, -1));

        txtName.setBorder(null);
        txtName.setOpaque(false);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 95, 119, 27));

        txtLocation.setOpaque(false);
        getContentPane().add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 136, 119, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 308, -1, -1));

        jLabel5.setText("Search by:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 55, -1, -1));

        rBNo.setSelected(true);
        rBNo.setText("depNo");
        rBNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBNoActionPerformed(evt);
            }
        });
        getContentPane().add(rBNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 48, -1, -1));

        rBName.setText("depName");
        getContentPane().add(rBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 48, -1, -1));

        rBLocation.setText("location");
        getContentPane().add(rBLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 48, -1, -1));

        txtSearch.setBackground(new java.awt.Color(204, 255, 204));
        txtSearch.setBorder(null);
        txtSearch.setOpaque(false);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 91, 304, 27));

        btnSerch.setText("Search");
        btnSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSerch, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 87, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 214, -1, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 214, -1, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 285, -1, -1));

        txtNo.setBackground(new java.awt.Color(0, 0, 0));
        txtNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNo.setOpaque(false);
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 54, 117, 27));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 837, 351));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setValues();
        d.add();
        clearData();
        d.getAllRows(tblTest);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnubdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubdateActionPerformed
        setValues();
        d.update();
        clearData();
        d.getAllRows(tblTest);
    }//GEN-LAST:event_btnubdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if(Tools.ConfirmMessege("Are you sure to delete this row?")){
        setValues();
        d.delete();
        clearData();
        d.getAllRows(tblTest);
      }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnGetAllRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllRowsActionPerformed
        d.getAllRows(tblTest);
    }//GEN-LAST:event_btnGetAllRowsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGroup.add(rBNo);
        btnGroup.add(rBName);
        btnGroup.add(rBLocation);
        
        Tools.setReport(tblTest);
         
        
        clearData();
        d.getAllRows(tblTest);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Tools.openForm(new frmMain());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String strDepNo= (String) Tools.inputBox("Enter Department no.");
        int DepNo = Integer.parseInt(strDepNo);
        d.setDepNo(DepNo);
        d.getOneRow(tblTest);
    }//GEN-LAST:event_btnFindActionPerformed

    private void tblTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestMouseClicked
        try {
            int row = tblTest.getSelectedRow();
            String strDepNo = tblTest.getValueAt(row, 0).toString();
            String strDepName = tblTest.getValueAt(row, 1).toString();
            String strDepLocation = tblTest.getValueAt(row, 2).toString();
            
            txtNo.setText(strDepNo);
            txtName.setText(strDepName);
            txtLocation.setText(strDepLocation); 
            
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(true);
            btnubdate.setEnabled(true);
        } catch (Exception e) {
            Tools.msgBox(e.getMessage());
        }
    }//GEN-LAST:event_tblTestMouseClicked

    private void tblTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTestMouseEntered

    private void btnSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerchActionPerformed
        String strSearch= "SELECT * FROM department WHERE ";
        if (rBNo.isSelected()) {
            strSearch += "depNo";
        } else if (rBName.isSelected()) {
            strSearch += "depName";
        } else {
            strSearch += "location";
        }
        strSearch += " LIKE '%" + txtSearch.getText()+ "%'";
        d.getCustomRows(strSearch, tblTest); 

    }//GEN-LAST:event_btnSerchActionPerformed

    private void rBNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBNoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tblTestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTestKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP ) {
              try {
            int row = tblTest.getSelectedRow();
            String strDepNo = tblTest.getValueAt(row, 0).toString();
            String strDepName = tblTest.getValueAt(row, 1).toString();
            String strDepLocation = tblTest.getValueAt(row, 2).toString();
            
            txtNo.setText(strDepNo);
            txtName.setText(strDepName);
            txtLocation.setText(strDepLocation); 
            
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(true);
            btnubdate.setEnabled(true);
        } catch (Exception e) {
            Tools.msgBox(e.getMessage());
        }
        }
    }//GEN-LAST:event_tblTestKeyPressed

    private void tblTestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTestKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP ) {
              try {
            int row = tblTest.getSelectedRow();
            String strDepNo = tblTest.getValueAt(row, 0).toString();
            String strDepName = tblTest.getValueAt(row, 1).toString();
            String strDepLocation = tblTest.getValueAt(row, 2).toString();
            
            txtNo.setText(strDepNo);
            txtName.setText(strDepName);
            txtLocation.setText(strDepLocation); 
            
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(true);
            btnubdate.setEnabled(true);
        } catch (Exception e) {
            Tools.msgBox(e.getMessage());
        }
        }
    }//GEN-LAST:event_tblTestKeyReleased

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Tools.printReport(tblTest, "Department");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnAdd;
    private controls.JMyButton btnBack;
    private controls.JMyButton btnClear;
    private controls.JMyButton btnDelete;
    private controls.JMyButton btnFind;
    private controls.JMyButton btnGetAllRows;
    private javax.swing.ButtonGroup btnGroup;
    private controls.JMyButton btnPrint;
    private controls.JMyButton btnSerch;
    private controls.JMyButton btnubdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rBLocation;
    private javax.swing.JRadioButton rBName;
    private javax.swing.JRadioButton rBNo;
    private javax.swing.JTable tblTest;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void clearData() {
        Tools.clearTxt(this);
        txtNo.setText(d.getAutoNumber());
        btnAdd.setEnabled(true);
        btnubdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtNo.requestFocus();
    }

    private void setValues() {
        d.setDepNo(Integer.parseInt(txtNo.getText()));
        d.setDepName(txtName.getText());
        d.setLocation(txtLocation.getText());
    }
}
